#the compose version, 3.x can fix docker-compose version 1.25.1,
version: "3.3"
services:
#nginx
  nginx:
    build: ./nginx
    image: wdf000/lnmp-nginx
    container_name: "lnmp-nginx"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - php
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./myWebApp:/myWebApp
    networks:
      - lnmp

#php
  php:
    build: ./php
    image: wdf000/lnmp-php
    container_name: "lnmp-php"
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./myWebApp:/myWebApp
    links:
      - mysql
    networks:
      - lnmp

#mysql
  mysql:
    build: ./mysql
    image: wdf000/lnmp-mysql
    container_name: "lnmp-mysql"
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - ./database:/var/lib/mysql
    networks:
      - lnmp

networks:
  lnmp:
    driver: bridge
